"use client";
import React, { useState } from "react";

function App() {
  const [stringsList] = useState([
    "Battered and Bruised",
    "Bioactive Spines",
    "Brutal Crush",
    "Carnivorous Contest",
    "Chunky Viscera",
    "Contemptful Rage",
    "Devour",
    "Digestive Acid",
    "Disembowel",
    "Feed",
    "Hardened Netting",
    "Hulking Crash",
    "Hungering Bellows",
    "Insatiable Rage",
    "Juggernaut Charge",
    "Ready to Feed",
    "Stalker's Netting",
    "Stalker's Webbing",
    "Swallowing Darkness",
    "Tenderized",
    "Venomous Lash",
    "Black Bulwark",
    "Black Sepsis",
    "Blood Pact",
    "Bloodcurdle",
    "Crimson Rain",
    "Goresplatter",
    "Grasp From Beyond",
    "Gruesome Disgorge",
    "Manifest Horror",
    "Seeping Transfusion",
    "Spectral Slam",
    "Spewing Hemorrhage",
    "The Unseeming",
    "Unseeming Blight",
    "Captain's Flourish",
    "Collapsing Nova",
    "Cosmic Residue",
    "Cosmic Shards",
    "Cosmic Simulacrum",
    "Decimate",
    "Expose",
    "Phase Blades",
    "Phase Lunge",
    "Rain of Arrows",
    "Shattering Sweep",
    "Acid Pools",
    "Acidic Carapace",
    "Acidic Eruption",
    "Acidic Stupor",
    "Caustic Hail",
    "Corrosion",
    "Enveloping Webs",
    "Erosive Spray",
    "Infested Bite",
    "Infested Spawn",
    "Lingering Erosion",
    "Rolling Acid",
    "Savage Assault",
    "Savage Wound",
    "Spinneret's Strands",
    "Spinneret's Websnap",
    "Sticky Webs",
    "Tacky Burst",
    "Tacky Threads",
    "Web Reave",
    "Catalyze Mutation",
    "Caustic Reaction",
    "Experimental Dosage",
    "Fixate",
    "Infest",
    "Ingest Black Blood",
    "Mutation: Accelerated",
    "Mutation: Necrotic",
    "Mutation: Ravenous",
    "Necrotic Wound",
    "Poison Burst",
    "Sanguine Overflow",
    "Sticky Web",
    "Unstable Infusion",
    "Vicious Bite",
    "Vile Discharge",
    "Volatile Concoction",
    "Web Eruption",
    "Assassination",
    "Atomized",
    "Chasmal Gash",
    "Dark Viscera",
    "Death Cloak",
    "Death Masks",
    "Eclipse",
    "Eternal Night",
    "Nether Rift",
    "Nexus Daggers",
    "Queensbane",
    "Reaper",
    "Regicide",
    "Stalking Shadows",
    "Starless Night",
    "Twilight Massacre",
    "Void Shredders",
    "Binding Webs",
    "Burning Rage",
    "Burrowed Eruption",
    "Call of the Swarm",
    "Cataclysmic Entropy",
    "Entangled",
    "Entropic Barrage",
    "Entropic Desolation",
    "Entropic Vulnerability",
    "Harden Carapace",
    "Impaled",
    "Impaling Eruption",
    "Mark of Death",
    "Mark of Paranoia",
    "Mark of Rage",
    "Mote of Overwrought Paranoia",
    "Mote of Unrelenting Rage",
    "Piercing Strike",
    "Poison Bolt",
    "Queen's Proclamation",
    "Reckless Charge",
    "Scarab Lord's Perseverance",
    "Seismic Upheaval",
    "Seismic Vulnerability",
    "Shatter Existence",
    "Shattered Shell",
    "Skittering Leap",
    "Spike Eruption",
    "Spike Storm",
    "Stinging Burst",
    "Stinging Delirium",
    "Stinging Swarm",
    "Strands of Reality",
    "Unleashed Swarm",
    "Venomous Rain",
    "Void Bolt",
    "Void Degeneration",
    "Void Step",
    "Web Bomb",
    "Web Vortex",
    "Whispers of The Silken Court",
    "Abyssal Conduit",
    "Abyssal Infusion",
    "Abyssal Reverberation",
    "Acid",
    "Acid Bolt",
    "Acid Explosion",
    "Acidic Apocalypse",
    "Acolyte's Essence",
    "Acrid Presence",
    "Cataclysmic Evolution",
    "Caustic Fangs",
    "Concentrated Toxin",
    "Conduit Collapse",
    "Conduit Ejections",
    "Consume",
    "Cosmic Apocalypse",
    "Cosmic Fallout",
    "Cosmic Rupture",
    "Dark Barrier",
    "Dark Detonation",
    "Devour",
    "Dreadful Presence",
    "Echoing Connection",
    "Essence Scarred",
    "Expulsion Beam",
    "Feast",
    "Froth Vapor",
    "Frothing Gluttony",
    "Frothy Toxin",
    "Gloom",
    "Gloom Blast",
    "Gloom Eruption",
    "Gloom Hatchling",
    "Gloom Orbs",
    "Gloom Splatter",
    "Gloom Touch",
    "Glutton Threads",
    "Gorge",
    "Grasping Silk",
    "Infest",
    "Infested Gloomburst",
    "Lingering Fallout",
    "Lingering Toxin",
    "Liquefy",
    "Null Detonation",
    "Oust",
    "Ousting Fragments",
    "Paralyzing Venom",
    "Paralyzing Waves",
    "Predation",
    "Predation Threads",
    "Queen's Summons",
    "Radiating Gloom",
    "Reaction Trauma",
    "Reaction Vapor",
    "Reactive Froth",
    "Reactive Toxin",
    "Royal Cocoon",
    "Royal Condemnation",
    "Royal Shackles",
    "Shadowblast",
    "Shadowgate",
    "Shadowy Distortion",
    "Silken Tomb",
    "Toxic Reaction",
    "Toxic Waves",
    "Venom Nova",
    "Web Blades",
    "Worshipper's Protection",
    "Wrest",
  ]);

  const sortedStrings = stringsList.slice().sort((a, b) => a.localeCompare(b));

  return (
    <div className="App">
      <h1>You are welcome!</h1>
      <pre>
        [
        {sortedStrings.map((str, index) => (
          <React.Fragment key={index}>
            {index !== 0 && ", "}'{str}'
          </React.Fragment>
        ))}
        ]
      </pre>
    </div>
  );
}

export default App;
